import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Sans, Inter_Tight } from "next/font/google";
import "./globals.css";
import { Providers } from "@/shared/context/global/providers";
import { cn } from "@/shared/lib/utils";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-display-family",
});

const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-sans-family",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full antialiased font-sans",
        geistSans.variable,
        geistMono.variable,
        instrumentSans.variable,
        interTight.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
